apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-web-deployment
  labels:
    app: chat-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-web
  template:
    metadata:
      labels:
        app: chat-web
    spec:
      containers:
      - name: chat-web
        image: chat-web:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
