apiVersion: v1
kind: Service
metadata:
  name: chat-ui-service
spec:
  type: NodePort
  selector:
    app: chat-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
